var discountsjson;
var discountedprices;
var tktsData='';
var profileJsondata='';
var CtrlWidgets=[];
var responsesdata=[];
var etid="";
var loginuserid='';
var evtdate='';
var eventid='';
var ticketsArray=[];
var tranid='';
var paymenttype;
var oid='';
var context='';;
var domain='';;
var ticketurl='';
var discountcode='';
var track='';
var serveradd;
var code;
var headers=new Object();
var timestamp;
var bfname='';
var blname='';
var bemail='';
var bphone='';
var paymentmode='';
var promotionenable=true;
var isavailableseat="";
var selectTktMsg='Please select ticket(s) Quantity';
var fbsharepopup="";


//seating level variables
var sectionid="";
var max_ticketid=new Object();
var min_ticketid=new Object();
var ticket_ids_seats=[];
var allsectionid=[];
var allsectionname=[];
var seatingsectionresponsedata=new Object();
var ticketseatcolor=new Object();
var mins_left = 14;
var s_left = 60;
var mins_remain=14;
var secs_remain=60;
var ticket_groupnames=new Object();
var notavailableticketids=new Array();
var memberseatticketids=new Array();
var seatingticketidresponse="";
var seating_enabled_tkt_wedget="NO";
var venueid="0";
var sel_seatcodes=new Array();
var sel_ticket=new Object();
var ticket_count=new Object();
var ids="";
var ticketnameids=new Object();
var seating_ticketids=new Array();
var seatposition="";
var section_sel_seats=new Object();
var seatinfo=new Object();
var button="<center><input type='button' value='Select Ticket' id='accept' onclick='closeit(\"Y\")'><input type='button' value='Cancel' id='cancel' onclick='closeit(\"N\")'></center>";
var sel_select=new Object();	
var seatcode_ticid=new Object();
var sel=false;
var count=0;
var reg_timeout='';
var layoutcount=0;
var ntsdata=new Object();
var fblogindata=new Object();
var becamepartner=false;
var ntscode="";
var display_ntscode="";
var fname="",lname="",email="";