var currencyObj={"USA":"USD","Albania":"ALL","Algeria":"DZL","Andorra":"EUR","Angola":"AOA","Anguilla":"XCD","Antigua and Barbuda":"XCD","Armenia":"AMD","Aruba":"AWG",
			"Argentina":"ARS","Australia":"AUD","Austria":"EUR","Azerbaijan Republic":"AZN","Bahamas":"BSD","Bahrain":"BHD","Barbados":"BBD","Belgium":"EUR",
			"Belize":"BZD","Benin":"XOF","Bermuda":"BMD","Bhutan":"BTN","Bolivia":"BOB","Bosnia and Herzegovina":"BAM","Botswana":"BWP","Brazil":"BRL","British Virgin Islands":"USD",
			"Brunei":"BND","Bulgaria":"BGN","Burkina Faso":"XOF","Burundi":"BIF","Cambodia":"KHR","Canada":"CAD","Cape Verde":"CVE","Cayman Islands":"KYD","Chad":"XAF",
			"China":"CNY","Chile":"CLP","Colombia":"COP","Comoros":"KMF","Costa Rica":"CRC","Cook Islands":"NZD","Croatia":"HRK","Cyprus":"EUR","Czech Republic":"CZK",
			"Denmark":"DKK","Democratic Republic of the Congo":"CDF","Djibouti":"DJF","Dominica":"XCD","Dominican Republic":"DOP","Ecuador":"USD",
			"El Salvador":"SVC","Eritrea":"ERN","Estonia":"EUR","Ethiopia":"ETB","Falkland Islands":"FKP","Faroe Islands":"DKK","Federated States of Micronesia":"",
			"Fiji":"FJD","Finland":"EUR","France":"EUR","French Guiana":"EUR","French Polynesia":"XPF","Gabon Republic":"XAF","Gambia":"GMD","Germany":"EUR",
			"Gibraltar":"GIP","Greenland":"DKK","Greece":"EUR","Grenada":"XCD","Guadeloupe":"EUR","Guatemala":"GTQ","Guinea":"GNF","Guinea Bissau":"XAF","Guyana":"GYD",
			"Honduras":"HNL","Hong Kong":"HKD","Hungary":"HUF","Iceland":"ISK","India":"INR","Indonesia":"IDR","Ireland":"EUR","Israel":"ILS","Italy":"EUR","Japan":"JPY",
			"Jamaica":"JMD","Jordan":"JOD","Kazakhstan":"KZT","Kenya":"KES","Kiribati":"AUB","Kuwait":"KWD","Kyrgyzstan":"KGS","Laos":"LAK","Latvia":"LVL","Lesotho":"LSL",
			"Liechtenstein":"CHF","Lithuania":"LTL","Luxembourg":"EUR","Madagascar":"MGA","Malaysia":"MYR","Malawi":"MWK","Maldives":"MVR","Mali":"XOF","Malta":"EUR",
			"Marshall Islands":"","Martinique":"EUR","Mauritania":"MRO","Mauritius":"MUR","Mayotte":"EUR","Mexico":"MXN","Mongolia":"MNT","Montserrat":"XCD",
			"Morocco":"MAD","Mozambique":"MZM","Namibia":"NAD","Nauru":"AUD","Nepal":"NPR","Netherlands":"EUR","Netherlands Antilles":"ANG","New Zealand":"NZD",
			"New Caledonia":"XPF","Nicaragua":"NIO","Niger":"XOF","Niue":"NZD","Norfolk Island":"AUD","Norway":"NOK","Oman":"OMR","Palau":"USD","Panama":"PAB","Papua New Guinea":"PGK",
			"Peru":"PEN","Philippines":"PHP","Pitcairn Islands":"NZD","Poland":"PLN","Portugal":"EUR","Qatar":"QAR","Republic of the Congo":"","Reunion":"EUR",
			"Romania":"RON","Russia":"RUB","Rwanda":"RWF","Saint Vincent and the Grenadines":"XCD","San Marino":"EUR","Samoa":"WST","ST Tome and Príncipe":"STD",
			"Saudi Arabia":"SAR","Senegal":"XOF","Seychelles":"SCR","Sierra Leone":"SLL","Singapore":"SGD","Slovakia":"EUR","Slovenia":"EUR","Solomon Islands":"SBD",
			"Somalia":"SOS","South Africa":"ZAR","South Korea":"KRW","Spain":"EUR","Sri Lanka":"LKR","St. Helena":"SHP","St. Kitts and Nevis":"XCD",
			"St. Lucia":"XCD","St. Pierre and Miquelon":"EUR","Suriname":"SRD","Svalbard and Jan Mayen Islands":"NOK","Swaziland":"SZL","Sweden":"SEK",
			"Switzerland":"CHF","Taiwan":"TWD","Tajikistan":"TJS","Tanzania":"TZS","Thailand":"THB","Togo":"XO","Tonga":"TOP","Trinidad and Tobago":"TTD","Tunisia":"TND",
			"Turkey":"TRY","Turkmenistan":"TMT","Turks and Caicos Islands":"USD","Tuvalu":"AUD","Uganda":"UGX","Ukraine":"UAH","United Arab Emirates":"AED",
			"United Kingdom":"EUR","Uruguay":"UYU","Vanuatu":"VUV","Vatican City State":"EUR","Venezuela":"VEF","Vietnam":"VND","Wallis and Futuna Islands":"XPF",
			"Yemen":"YER","Zambia":"ZMW"};
			
		