<%@taglib uri="/struts-tags" prefix="s" %>
 [{"eid":"<s:property value="eid"/>"
,"ticketData.ticketId":"<s:property value="ticketData.ticketId"/>"
,"ticketData.oldTicket":"<s:property value="ticketData.oldTicket"/>"
,"groupId":"<s:if test="%{(groupId) != ''}"><s:property value="groupId"/></s:if><s:else>0</s:else>"
,"ticketData.ticketName":"<s:property value="ticketData.ticketName"/>"
,"ticketData.ticketPrice":"<s:property value="ticketData.ticketPrice"/>" 
,"ticketData.totalTicketCount":"<s:property value="ticketData.totalTicketCount"/>"  
,"ticketData.ticketDescription":"<s:property value="ticketData.ticketDescription"/>"    
,"ticketData.minQty":"<s:property value="ticketData.minQty"/>"  
,"ticketData.maxQty":"<s:property value="ticketData.maxQty"/>"
,"ticketData.stdateTimeBeanObj.monthPart":"<s:property value="ticketData.stdateTimeBeanObj.monthPart"/>"
,"ticketData.stdateTimeBeanObj.ddPart":"<s:property value="ticketData.stdateTimeBeanObj.ddPart"/>"      
,"ticketData.stdateTimeBeanObj.yyPart":"<s:property value="ticketData.stdateTimeBeanObj.yyPart"/>"   
,"ticketData.stdateTimeBeanObj.hhPart":"<s:property value="ticketData.stdateTimeBeanObj.hhPart"/>"      
,"ticketData.stdateTimeBeanObj.mmPart":"<s:property value="ticketData.stdateTimeBeanObj.mmPart"/>"       
,"ticketData.stdateTimeBeanObj.ampm":"<s:property value="ticketData.stdateTimeBeanObj.ampm"/>"     
,"ticketData.enddateTimeBeanObj.monthPart":"<s:property value="ticketData.enddateTimeBeanObj.monthPart"/>"     
,"ticketData.enddateTimeBeanObj.ddPart":"<s:property value="ticketData.enddateTimeBeanObj.ddPart"/>"      
,"ticketData.enddateTimeBeanObj.yyPart":"<s:property value="ticketData.enddateTimeBeanObj.yyPart"/>"      
,"ticketData.enddateTimeBeanObj.hhPart":"<s:property value="ticketData.enddateTimeBeanObj.hhPart"/>"      
,"ticketData.enddateTimeBeanObj.mmPart":"<s:property value="ticketData.enddateTimeBeanObj.mmPart"/>"       
,"ticketData.enddateTimeBeanObj.ampm":"<s:property value="ticketData.enddateTimeBeanObj.ampm"/>"    
,"ticketData.processFeePaidBy":"<s:property value="ticketData.processFeePaidBy"/>"       
,"ticketData.processingFee":"<s:property value="ticketData.processingFee"/>"  
,"ticketData.isAttendee":"<s:property value="ticketData.isAttendee"/>"   
,"ticketData.isScanCode":"<s:property value="ticketData.isScanCode"/>"}]


